title: ğŸ¤—ğŸ¤— ã€RAG+Toolsã€‘åŸºäºErnie-Botæ‰“é€ ä¼ä¸šçº§Agentåº”ç”¨
sidebar_title: ğŸ„ï¸ User Config
version: 1.0-beta
logo: /home/aistudio/paddle.png
logo_width: 300
ProjectIntroduction: é£æ¡¨ï¼ˆPaddlePaddleï¼‰ä»¥ç™¾åº¦å¤šå¹´çš„æ·±åº¦å­¦ä¹ æŠ€æœ¯ç ”ç©¶å’Œä¸šåŠ¡åº”ç”¨ä¸ºåŸºç¡€ï¼Œé›†æ ¸å¿ƒæ¡†æ¶ã€åŸºç¡€æ¨¡å‹åº“ã€ç«¯åˆ°ç«¯å¼€å‘å¥—ä»¶ã€ä¸°å¯Œçš„å·¥å…·ç»„ä»¶ã€æ˜Ÿæ²³ç¤¾åŒº [47]äºä¸€ä½“ï¼Œæ˜¯ä¸­å›½é¦–ä¸ªè‡ªä¸»ç ”å‘ã€åŠŸèƒ½ä¸°å¯Œã€å¼€æºå¼€æ”¾çš„äº§ä¸šçº§æ·±åº¦å­¦ä¹ å¹³å°ã€‚ [1-2]é£æ¡¨åœ¨ä¸šå†…ç‡å…ˆå®ç°äº†åŠ¨é™ç»Ÿä¸€çš„æ¡†æ¶è®¾è®¡ï¼Œå…¼é¡¾ç§‘ç ”å’Œäº§ä¸šéœ€æ±‚ï¼Œåœ¨å¼€å‘ä¾¿æ·çš„æ·±åº¦å­¦ä¹ æ¡†æ¶ã€å¤§è§„æ¨¡åˆ†å¸ƒå¼è®­ç»ƒã€é«˜æ€§èƒ½æ¨ç†å¼•æ“ã€äº§ä¸šçº§æ¨¡å‹åº“ç­‰æŠ€æœ¯ä¸Šå¤„äºå›½é™…é¢†å…ˆæ°´å¹³ã€‚

# LLM
LLM_API:
  ernie-3.5:
    api_type: aistudio
    access_token: fa07b9430506b7349bdc36848f8781fa818a0ce8
  ernie-4.0:
    api_type: aistudio
    access_token: fa07b9430506b7349bdc36848f8781fa818a0ce8

# Encoder
encoder_batch_size: 16
Encoder:
  ErnieBot-Text-Embedding:
    api_type: aistudio
    access_token: fa07b9430506b7349bdc36848f8781fa818a0ce8

# text splitter
SENTENCE_SIZE: 500
# LLM å‚æ•°
top_k: 5
Parameter:
  max_length:
    min_value: 0
    max_value: 4096
    default: 1024
    step: 1
    tip: ç”Ÿæˆç»“æœæ—¶çš„æœ€å¤§tokenæ•°
  top_p:
    min_value: 0.0
    max_value: 1.0
    default: 0.7
    step: 0.01
    tip: ç”¨äºæ§åˆ¶æ¨¡å‹ç”Ÿæˆæ–‡æœ¬æ—¶ï¼Œé€‰æ‹©ä¸‹ä¸€ä¸ªå•è¯çš„æ¦‚ç‡åˆ†å¸ƒçš„èŒƒå›´ã€‚
  temperature:
    min_value: 0.01
    max_value: 1.0
    default: 0.7
    step: 0.01
    tip: ç”¨äºè°ƒæ•´æ¨¡å‹ç”Ÿæˆæ–‡æœ¬æ—¶çš„åˆ›é€ æ€§ç¨‹åº¦ï¼Œè¾ƒé«˜çš„temperatureå°†ä½¿æ¨¡å‹æ›´æœ‰å¯èƒ½ç”Ÿæˆæ–°é¢–ã€ç‹¬ç‰¹çš„æ–‡æœ¬ï¼Œè€Œè¾ƒä½çš„æ¸©åº¦åˆ™æ›´æœ‰å¯èƒ½ç”Ÿæˆå¸¸è§æˆ–å¸¸è§„çš„æ–‡æœ¬

# çŸ¥è¯†åº“å­˜å‚¨
upload_dir: assets/raw_upload_files
vector_db_path: assets/db/DefaultVector.db

# Tools
Tools:
  Translation:
    description: æ–‡æœ¬ç¿»è¯‘å·¥å…·

Tools_Access_Token: fa07b9430506b7349bdc36848f8781fa818a0ce8

# question
question: ['è¯·é€‰æ‹©','å¹³å°æ”¯æŒå“ªç§å¼€å‘æ–¹å¼','å¹³å°æ”¯æŒå“ªç§å¼€å‘æ–¹å¼ï¼Œå¦‚æœä½ ç»™å‡ºçš„ç­”æ¡ˆæ˜¯ä¸­æ–‡ï¼Œè¯·å¸®æˆ‘å°†å®ƒç¿»è¯‘æˆè‹±æ–‡']


# Prompt
DEFAULT_PROMPT: ä½ æ˜¯ä¸€ä½AI Studioé£æ¡¨æ˜Ÿæ²³ç¤¾åŒºçš„èµ„æ·±ç”¨æˆ·ã€‚è¯·ä»ç»™å®šçš„æ–‡ç« ä¸­ï¼Œæå–å‡ºèƒ½å›ç­”ä»¥ä¸‹é—®é¢˜çš„ç­”æ¡ˆã€‚ \n\n é—®é¢˜ï¼š$query \n\n å¦‚æœæ–‡ä¸­æ²¡æœ‰ç­”æ¡ˆï¼Œè¯·å›å¤â€œæ²¡æ‰¾åˆ°ç­”æ¡ˆâ€ã€‚ \n\n æ–‡ç« ï¼š$context \n\n è¯·ç¡®ä¿ä½ çš„å›ç­”å‡†ç¡®ã€ç®€æ´ï¼Œå¹¶å°½é‡æä¾›åŸæ–‡ä¸­çš„å…³é”®ä¿¡æ¯ã€‚
